//
//  ZoozSDKWrapper.h
//  JackpotRising
//
//  Created by Mathews Philip on 15/07/16.
//  Copyright © 2016 Jackpot Rising Inc. All rights reserved.
//



/**
 *  call initialize() method to init the object of ZoozSDK
 *  call setDelegate() method to set the delegate of Wrapperclass to the invoking class
 *  call addCreditCard() method to add CreditCard to payment gateway
 */



#import <Foundation/Foundation.h>

@interface ZoozWrapperPaymentObject : NSObject

@property (nonatomic, retain) NSString *expirationMonth;
@property (nonatomic, retain) NSString *expirationYear;
@property (nonatomic, retain) NSString *cardHolderName;
@property (nonatomic, retain) NSString *cvvNumber;
@property (nonatomic, retain) NSString *cardNumber;
@property (nonatomic, retain) NSString *userIdNumber;

@end

@protocol zoozWrapperDelegate <NSObject>

/**
 *  Delegate method fired when token is succesfully generated
 *
 *  @param token - PaymentMethodToken generated by Zooz
 */
- (void)generateTokenSuccessful: (NSString *) token;

/**
 *  Delegate method fired when token generation fails
 *
 *  @param message - Error message
 */
- (void)generateTokenFailed: (NSString* ) message;

@end


@interface ZoozSDKWrapper : NSObject

/**
 *  to initialize the ZoozSDKWrapper object
 *
 *  @return ZoozSDKWrapper object
 */
+ (ZoozSDKWrapper *) initialize;

/**
 *  to inititalize ZoozWrapperPaymentObject
 *
 *  @return - ZoozWrapperPaymentObject
 */
- (ZoozWrapperPaymentObject *) getZoozWrapperPaymentObject;

/**
 *  to set ZoozSDKWrapperdelegates
 *
 *  @param delegate - delegate object to the invoking class
 */
- (void) setZoozDelegate: (id<zoozWrapperDelegate>) delegate;

/**
 *  to add a Credit Card to the Zooz payment gateway
 *
 *  @param token                - pre auth token
 *  @param email                - email ID of account holder
 *  @param paymentMethodDetails - credit card info as ZoozPaymentMethodDetails
 */
- (void) addCreditCard:(NSString *)token emailAddress:(NSString *)email paymentMethodDetails:(ZoozWrapperPaymentObject *)paymentMethodDetails andBillingAddress:(NSDictionary*)addressJSON;

@end
